from email.message import EmailMessage
from confidential import password
import ssl
import smtplib


email_sender = 'bworks84@gmail.com'
email_password = password


email_receiver = 'bahov42190@lutota.com'

subject = 'Rob\'s auto-generated email with python'

body = """
Hey this is an email generated by a Python script
"""
# create instance of Class with following attributes
em = EmailMessage()
em['From'] = email_sender
em['To'] = email_receiver
em['subject'] = subject
em.set_content(body)

context = ssl.create_default_context()

with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
    smtp.login(email_sender, email_password)
    smtp.sendmail(email_sender, email_receiver, em.as_string())
